### ISSUE TITLE
Something's breaking with local collection roles and ansible-base / acd

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-content-testing#17]
Also, ACD is no longer ACD, it is "ansible" and ansible that used to be "ansible" is ansible-base.

**Comment by geerlingguy** [comment]
https://github.com/ansible-community/antsibull/issues/136

**Comment by geerlingguy** [comment]
Related: https://github.com/ansible-community/molecule/issues/2755

**Comment by geerlingguy** [comment]
Playbook:

```
---
- hosts: localhost
  connection: local

  tasks:
    - name: Test running two same-named roles in separate collections.
      include_tasks: tasks/same-name-roles.yml
```

Contents of `same-name-roles.yml`:

```
---
- name: Include a 'test' role from 'example.one' collection.
  include_role:
    name: example.one.test

- name: Check example.one.test file.
  stat:
    path: /tmp/example.one.test
  register: example_one_test

- name: Assert that example.one.test role ran.
  assert:
    that: example_one_test.stat.exists

- name: Include a 'test' role from 'example.two' collection.
  include_role:
    name: example.two.test

- name: Check example.two.test file.
  stat:
    path: /tmp/example.two.test
  register: example_two_test

- name: Assert that example.two.test role ran.
  assert:
    that: example_two_test.stat.exists
```

And here are those collections: https://github.com/geerlingguy/ansible-content-testing/tree/master/ansible_collections/example
