### ISSUE TITLE
Add custom plugin that imports from a module_util in community.general

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-content-testing#8]
When looking at some other examples relating to the tombstoning PR (see #7), I realized I should also add a plugin that imports from a `module_util` that was moved out of ansible core, to make sure that redirection is working correctly for those who have custom Jinja filters or plugins.

**Comment by geerlingguy** [comment]
Something simple, using https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/module_utils/known_hosts.py:

```python
from ansible.module_utils.known_hosts import is_ssh_url

def is_ssh_url_test(url):
    return is_ssh_url(url)

class TestModule(object):
    def tests(self):
        return dict(is_ssh_url=is_ssh_url_test)
```

**Comment by geerlingguy** [comment]
Added. Slightly modified for a more semantic usage:

```yaml
---
- hosts: all

  tasks:
    - name: Test custom ssh_url test plugin.
      assert:
        that:
          - not_ssh_url is not ssh_url
          - real_ssh_url is ssh_url
```
